In [1]:
import pandas as pd
import numpy as np

In [16]:
# save links only edit once -- if they change
confirmed = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
deaths = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv"
recovered = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv"

links_list = [confirmed, deaths, recovered]

# use list comp to read links 
list_dat = [pd.read_csv(link) for link in links_list]

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20
0,NaN,Thailand,15.0000,101.0000,0,0,0,0,2,2,...,33,34,34,35,35,35,35,41,42,42
1,NaN,Japan,36.0000,138.0000,0,0,0,0,1,1,...,101,118,118,118,118,118,144,144,144,150
2,NaN,Singapore,1.2833,103.8333,0,0,0,0,0,0,...,78,96,96,97,105,105,109,114,114,114
3,NaN,Nepal,28.1667,84.2500,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
4,NaN,Malaysia,2.5000,112.5000,0,0,0,0,0,0,...,24,26,26,26,35,42,42,49,60,75
5,British Columbia,Canada,49.2827,-123.1207,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4
6,New South Wales,Australia,-33.8688,151.2093,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4
7,Victoria,Australia,-37.8136,144.9631,0,0,0,0,0,0,...,7,7,7,8,8,8,8,8,8,8
8,Queensland,Australia,-28.0167,153.4000,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,8
9,NaN,Cambodia,11.5500,104.9167,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
10,NaN,Sri Lanka,7.0000,81.0000,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,3
11,NaN,Germany,51.0000,9.0000,0,0,0,0,0,0,...,18,25,25,46,46,46,67,67,105,113
12,NaN,Finland,64.0000,26.0000,0,0,0,0,0,0,...,1,1,1,1,1,10,10,10,10,10
13,NaN,United Arab Emirates,24.0000,54.0000,0,0,0,0,0,0,...,12,17,17,17,17,23,23,23,26,31
14,NaN,Philippines,13.0000,122.0000,0,0,0,0,0,0,...,2,2,2,2,2,2,2,5,5,8
15,NaN,India,21.0000,78.0000,0,0,0,0,0,0,...,4,4,4,4,4,13,13,14,14,15
16,NaN,Italy,43.0000,12.0000,0,0,0,0,0,0,...,724,1045,1045,1439,1966,2335,2749,2941,4025,4440
17,NaN,Sweden,63.0000,16.0000,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,16
18,NaN,Spain,40.0000,-4.0000,0,0,0,0,0,0,...,32,183,183,193,517,517,530,1028,1081,1107
19,South Australia,Australia,-34.9285,138.6007,0,0,0,0,0,0,...,2,2,2,3,3,3,3,3,3,3
20,NaN,Belgium,50.8333,4.0000,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,31,31
21,NaN,Egypt,26.0000,30.0000,0,0,0,0,0,0,...,1,27,27,27,27,21,27,32,32,32
22,From Diamond Princess,Australia,35.4437,139.6380,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,NaN,Lebanon,33.8547,35.8623,0,0,0,0,0,0,...,1,1,1,1,1,1,1,3,3,4
24,NaN,Iraq,33.0000,44.0000,0,0,0,0,0,0,...,3,15,15,24,26,26,26,32,43,43
25,NaN,Oman,21.0000,57.0000,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,12,12
26,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
27,NaN,Bahrain,26.0275,50.5500,0,0,0,0,0,0,...,22,35,35,44,44,60,77,81,88,100
28,NaN,Kuwait,29.5000,47.7500,0,0,0,0,0,0,...,1,2,5,5,5,5,9,9,15,18
29,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,0,0,8,8,12,12,12,12,12,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Mayotte,France,-12.8275,45.1662,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
439,NaN,Uzbekistan,41.3775,64.5853,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
440,Netherlands,Netherlands,52.1326,5.2913,0,0,0,0,0,0,...,0,0,0,0,2,2,2,2,2,2
441,Nova Scotia,Canada,44.6820,-63.7443,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
442,Guadeloupe,France,16.2500,-61.5833,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
443,NaN,Benin,9.3077,2.3158,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
444,NaN,Liberia,6.4281,-9.4295,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
445,Curacao,Netherlands,12.1696,-68.9900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
446,NaN,Somalia,5.1521,46.1996,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
447,NaN,Tanzania,-6.3690,34.8888,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
448,Virgin Islands,US,18.3358,-64.8963,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
449,Cayman Islands,United Kingdom,19.3133,-81.2546,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
450,Reunion,France,-21.1351,55.2471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
451,NaN,Barbados,13.1939,-59.5432,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
452,NaN,Montenegro,42.5000,19.3000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
453,NaN,Kyrgyzstan,41.2044,74.7661,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
454,NaN,Mauritius,-20.2000,57.5000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
455,Aruba,Netherlands,12.5186,-70.0358,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
456,NaN,Zambia,-15.4167,28.2833,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
457,NaN,Djibouti,11.8251,42.5903,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
458,NaN,"Gambia, The",13.4432,-15.3101,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
459,Montserrat,United Kingdom,16.7425,-62.1874,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
460,NaN,"Bahamas, The",25.0343,-77.3963,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
461,Greenland,Denmark,71.7069,-42.6043,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
462,New Caledonia,France,-20.9043,165.6180,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
463,Bermuda,United Kingdom,32.3078,-64.7505,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
464,NaN,Chad,15.4542,18.7322,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
465,NaN,El Salvador,13.7942,-88.8965,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
466,NaN,Fiji,-17.7134,178.0650,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
467,NaN,Nicaragua,12.8654,-85.2072,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0